name: build and push docker image
on:
  push:
    branches: 
      - 'main'

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GHREPO: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
      TAG: $(date +%Y%m%d_%H%M)

    steps:
    - uses: actions/checkout@v4

    - name: login
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: build
      run: |
        docker build . --no-cache --file Dockerfile --tag $GHREPO:$TAG
        docker tag $GHREPO:$TAG $GHREPO:latest

    - name: push
      run: |
        docker push $GHREPO:$TAG
        docker push $GHREPO:latest
